### ISSUE TITLE
Default value not checking

### ISSUE THREAD

**Issue by rafamrs** [mansona/ember-radio-buttons#17] opened 2016-11-15 12:42 UTC
I have a default value on the checked variable, but it isn't checking de radio.

Template code:
```handlebars
{{point.rate}} // here it prints to the template the value "2" correctly
{{radio-button value="3" checked=point.rate class="rating-input" id="rating-input-3"}}
{{radio-button value="2" checked=point.rate class="rating-input" id="rating-input-2"}}
{{radio-button value="1" checked=point.rate class="rating-input" id="rating-input-1"}}
```

Controller code:
```js
this.set('point', {rate: 2});
```

Any idea why number 2 radio is not getting checked by default?

**Comment by mansona** [comment] 2016-11-15 13:12
hey @ptraceur thanks for the issue report. 

I don't know exactly what your use case is but you're facing an issue with references to objects in Javascript. In the line here `{{radio-button value="3" checked=point.rate class="rating-input" id="rating-input-3"}}` you are making the radio button watch the `rate` parameter in the `point` object. Then when you call `this.set('point', {rate: 2});` in the controller you are *replacing the whole object out from under the component* and Ember is loosing track of it somewhere. 

I don't get the impression that doing something like `this.set('point', {rate: 2});` is the "Ember way" of doing this. Can you try `this.set('point.rate', 2);` and let me know how you get on?

**Comment by ptraceur** [comment] 2016-11-15 13:20
Hi @mansona, thanks for the fast reply. 

I tried the way you suggest, but it still doesn't work as expected. And tried the following too, without any difference:

```js
Ember.set(this.point, 'rate', 2);
```

**Comment by mansona** [comment] 2016-11-15 13:47
@ptraceur are you able to create a failing test for this? 

If not I can take a look at making the test and attempt a fix at some point in the next few weeks 👍

**Comment by ptraceur** [comment] 2016-11-15 14:19
Sorry, I can't right now. I'm full of work and the code is too complex.

**Comment by mansona** [comment] 2016-11-15 15:19
Cool, in that case, I'll take a look at some point over the next few weeks 👍 

Re: code being too complex, this is just a standard Ember addon with very few additions past the generated starting point. The main code is here: https://github.com/stonecircle/ember-radio-buttons/blob/master/addon/components/radio-button.js and a very basic test can be found here https://github.com/stonecircle/ember-radio-buttons/blob/master/tests/unit/components/radio-button-test.js, and that's about it 😄 

I know you said you are busy, I just thought that if you or anyone else reading this wanted to add a test I best point in the right direction 👍

**Comment by ptraceur** [comment] 2016-11-16 10:58
@mansona Hi again,

I think I know what the problem is. At `ember-radio-buttons/addon/components/radio-button.js` computed `htmlChecked` I've added a console.log in the first line with the following code:

```js
console.log(this.get('value'), this.get('checked'));
```

After I restarted ember with `ember s`, I've noticed the following in my browser console:

![screen shot 2016-11-16 at 10 55 10](https://cloud.githubusercontent.com/assets/924985/20344566/34118e2a-abeb-11e6-970d-bb8c3d05043b.jpg)

As you can see by the colors, `this.get('value')` are strings and `this.get('checked')` are integers. So I've to make sure the variable in checked is always a string, and if not, convert it to a string. Would this be better on the plugin side or from my code?

**Comment by mansona** [comment] 2019-11-10 17:50
I'm closing this issue because it's super old 🙈 do let me know if this is still a problem for you and we can look to get it covered in a test 👍

**Closed by mansona** 2019-11-10 17:50 UTC
Labels: needs test
